name = "Jinkies"
uuid = "cd0adc42-0d61-404c-a6a1-590b90f15aef"
authors = ["TheCedarPrince <jacobszelko@gmail.com> and contributors"]
version = "0.0.1"

[deps]
WiringPi = "56b06491-0088-44d9-858f-9bc194f2c904"

[compat]
WiringPi = "0.2.2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
